### ISSUE TITLE
OT flex support

### ISSUE THREAD

**Issue by ashah03** [PyLabRobot/pylabrobot#197]
Any plans to support the Opentrons Flex robot?

**Comment by rickwierenga** [comment]
Sure, but we don't currently have anyone with this robot. Do you have one? Do you want to work on this?

**Comment by ashah03** [comment]
Not yet, but I may get one / be able to help in the future

**Comment by rickwierenga** [comment]
Grea! Let me know!

**Comment by rickwierenga** [comment]
closing this for now

**Comment by dabdoue** [comment]
I have a Flex and am interested in this software. I have a pretty quick turnaround for a project where I want to use the Flex along with a 6 axis robot in a ROS2 environment, and having access to software like this would be fantastic for future modularity.

Please feel free to reach out to me on my LinkedIn (GH profile) so we can establish more formal and personal communication

**Comment by rickwierenga** [comment]
sounds cool! would be down to write backend for the flex and/or robot arm?
