### ISSUE TITLE
Add flowmi strainers

### ISSUE THREAD

**Issue by fderop** [PyLabRobot/pylabrobot#210]
Flowmi produces [neat strainers](https://www.sigmaaldrich.com/US/en/product/sigma/bah136800040) that you can put on a pipette tip. I want to implement this in PLR. I think we could reuse a lot of code from TipRack, but I'm not sure what the best procedure would be to do the actual pickup motion. Any suggestions? The normal use case would be:
1. Pick up tip
2. Aspirate something
3. Pick up a flowmi strainer
4. Dispense
5. Discard

**Comment by rickwierenga** [comment]
i think this can be a method on LH, `pick_up_stainer`. This can use the `move_channel_{x,y,z}` of the backend.

**Comment by rickwierenga** [comment]
can i close this?
