### ISSUE TITLE
ItemizedResource: inconsistency in docstrings of dy, dx, dz and calculated coordinates

### ISSUE THREAD

**Issue by naikymen** [PyLabRobot/pylabrobot#259]
Hi! I'm confused by a behaviour here.

The docstrings state:

    dx: The bottom left corner for items in the left column
    dy: The bottom left corner for items in the top row
    dz: The z coordinate for all items

From this, I interpret that "dy" is the Y coordinate of the bottom-left corner of the items (e.g. Wells) in the top row (i.e. row A) of the ItemizedResource (e.g. A1, A2, etc.).

![image](https://github.com/user-attachments/assets/2270eba1-2577-46a3-983f-af7ffa76fb34)

The `Eppendorf_96_wellplate_250ul_Vb` plate, for example, sets `dy=8.26`, which is suspiciously small.

![image](https://github.com/user-attachments/assets/a23b281a-2b01-4b51-a3c4-930dade06c34)

On inspection of the Wells in column 1, `dy` ends up being the Y coordinate of the items in the **bottom** row of the ItemizedResource (i.e. H1, H2, ...), and the Well in the top row has a much larger value.

![image](https://github.com/user-attachments/assets/6b169bf5-7861-4b85-baf7-114f9fff382f)

What am I getting wrong?

Best!
N

**Comment by rickwierenga** [comment]
yes, you found a bug in the documentation, should be the bottom row :)

I'm currently working on big changes to the docs (https://github.com/PyLabRobot/pylabrobot/pull/249), will fix, thanks for flagging :)

**Comment by rickwierenga** [comment]
https://github.com/PyLabRobot/pylabrobot/commit/6d48b34de78f0b727a200030427d9c3e176a2834 (was actually just in doc strings)

**Comment by naikymen** [comment]
Good to know.

![image](https://github.com/user-attachments/assets/be2686b9-fa9a-4fd5-a6b9-a3754dfff9d5)

**Comment by naikymen** [comment]
In the meantime, looking for some plate to use as a reference, I found that that Thermo plate does not match the dimensions in the datasheet exactly.

I've marked that here for now: https://gitlab.com/pipettin-bot/forks/pylabrobot/-/commit/6c470a129d87b031dd6210512c59b6721f6714d1#21ca88187b01ddf8498db898ec7fd86de595d156

Is this usually the case with the definitions of labware in PLR?

**Comment by rickwierenga** [comment]
it happens that data in these datasheets does not exactly correspond with what we see in reality. i think physical reality should take precedence

(I have been encouraging people to start separate threads for better searchability :))
