### ISSUE TITLE
pip installation broken

### ISSUE THREAD

**Issue by melkonyan** [PyLabRobot/pylabrobot#29]
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from pylabrobot.resources.hamilton import STARLetDeck

ModuleNotFoundError: No module named 'pylabrobot.resources'
```

Steps to reproduce: 

```
pip install pylabrobot
pip isntall pylabrobot[all]
```

Then trying to run simulator code from [documentation](https://docs.pylabrobot.org/using-the-simulator.html)

Python: 3.8
OS: linux (ubuntu)

**Comment by melkonyan** [comment]
installation from source code works

**Comment by rickwierenga** [comment]
Thank you for reporting this. This is caused by the PyPI version being outdated. I will update it soon.
