### ISSUE TITLE
Error in plates definitions

### ISSUE THREAD

**Issue by tianar** [PyLabRobot/pylabrobot#32]
A Tecan plate definition results in error:
```
AssertionError: Well max volume computation currently assumes circular wells
```
After looking into the `pylabrobot/resources/tecan/plates.py` module I realize there are most likely typos in the definitions of `size_x`, `size_y` for `Microplate_48_Well`, `Microplate_24_Well`, `CaCo2_Plate_24_Well` plates. 
 
A quick search shows that `size_x!=size_y` for `Cos_96_ProtCryst` in `corning_costar` as well.

**Comment by rickwierenga** [comment]
Thank you for filing these issues!

The Tecan plates should be fixed with https://github.com/PyLabRobot/pylabrobot/commit/0b468a4f9b17dc7b2fec1d35d0dcdab4431d220b.

I double checked and the definition for `Cos_96_ProtCryst` appears to be correct, or at least consistent with Venus' definition.
