### ISSUE TITLE
Volume tracker does not properly compute well volume based on height of container

### ISSUE THREAD

**Issue by ben-ray** [PyLabRobot/pylabrobot#44]
I noticed that these 3 labware:
```
Cos_96_DW_2mL
Cos_96_DW_1mL
Cos_96_EZWash
```
All have the same computed max volume of 572.5552611167398 when I call `.get_item(0).tracker.get_free_volume()`

For example:
```
plt_car = PLT_CAR_L5AC_A00(name="plt_car")
plt_car[0] = Cos_96_DW_2mL(name="reag_dw_plt")
reag_plt = lh.get_resource("reag_dw_plt")
reag_plt.get_item(0).tracker.get_free_volume()
```

It seems like the volume tracker is not properly calculating the well volume? As a user, it feels most convenient to just directly define this.

Full complexity of physical reality:
When an empty pipette tip plunges to the bottom of a reagent well, it displaces a volume of liquid & I must make sure the volume of liquid in the well + this displaced volume is less than the total volume that can be contained within the height of the well. Otherwise, liquid will spill into nearby wells. Ideally, this could be detected as an illegal operation automatically. By default, the pipette could begin aspiration steps at a determined height move -Z during the aspiration as to maximize usable volume within a well. Something similar could occur for dispenses. But, maybe this introduces too much complexity. A design choice: should default, non-illegal behavior cause the liquid to spill over to nearby wells?

**Comment by rickwierenga** [comment]
This should actually be addressed by https://github.com/PyLabRobot/pylabrobot/commit/c4930a367207e75e0f35ff6e430d41b824a9212c.

I'm not sure if the plunger moving into the container is something we can accurately predict in all cases, and could potentially be an inconvenience to other users. It's probably better to manually adjust the max volume of a well.
