### ISSUE TITLE
assign_resource missing from LiquidHandler

### ISSUE THREAD

**Issue by marcosfelt** [PyLabRobot/pylabrobot#5]
It seems the `assign_resource` method is missing from the `LiquidHandler` class. I get the following error:

```bash
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [7], line 1
----> 1 lh.assign_resource(tip_car, rails=1, replace=True)

AttributeError: 'LiquidHandler' object has no attribute 'assign_resource'
```

Was this unintentionally deleted in a recent commit?

**Comment by rickwierenga** [comment]
This has been replaced with `lh.deck.assign_child_resource`.

Is the code above from one of the official samples? (except `basic.ipynb`, which I'm updating today when I get access to the robot)

**Comment by marcosfelt** [comment]
Perfect! It's actually in `using_the_simulator.ipynb`.  I have a couple things I noticed that could make that notebook clearer. Should I send in a PR?

**Comment by rickwierenga** [comment]
That’d be great! Thanks in advance.
