### ISSUE TITLE
Visualizer

### ISSUE THREAD

**Issue by BenyaPyat** [PyLabRobot/pylabrobot#75]
I'm currently attempting to access the visualizer following the following documentation: https://docs.pylabrobot.org/using-the-visualizer.html

I keep running into issues however where the code would work, however the visualization on the server would look like this: 

![image](https://github.com/PyLabRobot/pylabrobot/assets/69654071/a1f4353e-d711-4e15-91d8-0e412445c0ad)

From my understanding all the code matches with the git, and I assume the issue is somewhere in index.html in the Visualizer folder under pylabrobot, however I'm not sure how to resolve this issue.

Thank you

**Comment by rickwierenga** [comment]
Could you open the console and share a screenshot of what you see there after reloading the page?

**Comment by BenyaPyat** [comment]
![image](https://github.com/PyLabRobot/pylabrobot/assets/69654071/08da1060-34a4-4ea3-ba9a-2b3084909787)

![image](https://github.com/PyLabRobot/pylabrobot/assets/69654071/e3fc64ce-5784-43e4-97dd-666f24350f7b)

**Comment by rickwierenga** [comment]
Thanks!

Your browser has a JavaScript console, could  you share an image of that as well? It differs per browser how to open this. What browser and which OS are you using?

**Comment by BenyaPyat** [comment]
I'm using Chrome, and windows but with ubuntu console installed on it, what do you mean by javascript console? As in the inspect element?

**Comment by rickwierenga** [comment]
Yes. Go to the console tab. The shortcut is likely Shift + CTRL + J .

**Comment by BenyaPyat** [comment]
![image](https://github.com/PyLabRobot/pylabrobot/assets/69654071/b07bc240-f286-4f9c-b378-285c24ae8059)

**Comment by BenyaPyat** [comment]
Looking through which files I have: 

![image](https://github.com/PyLabRobot/pylabrobot/assets/69654071/3843b131-4508-4852-8481-34ecf8a168da)

Not sure why it's throwing no file found, they seem to be present

**Comment by rickwierenga** [comment]
What is the directory you're running the jupyter notebook from?

(I just ran it from the pylabrobot root directory: where the README etc. live in a freshly cloned instance and it worked fine)

**Comment by BenyaPyat** [comment]
I'm currently running it out of visualizer in a git clone of pylabrobot

**Comment by rickwierenga** [comment]
Could you run it from the project root?

**Comment by BenyaPyat** [comment]
I just tried running it from the root where the README.txt is and I got the same thing

**Comment by BenyaPyat** [comment]
The root being pylabrobot

**Comment by BenyaPyat** [comment]
No I did a git clone

**Comment by rickwierenga** [comment]
You will still need to install it. Preferably in a local virtual environment. https://docs.pylabrobot.org/installation.html#from-source

**Comment by BenyaPyat** [comment]
Oh my apologies I thought you were referring to pip installing pylabrobot, I did pip install -e '.[dev]'

**Comment by rickwierenga** [comment]
No worries! Is it working now?

**Comment by BenyaPyat** [comment]
No, I had it installed beforehand as well when I did the initial installation

**Comment by rickwierenga** [comment]
Could you print the `path` and the contents of this directory after:

```py
dirname = os.path.dirname(__file__)
path = os.path.join(dirname, ".")
if not os.path.exists(path):
  raise RuntimeError("Could not find Visualizer files. Please run from the root of the "
                     "repository.")
```

around line 314 in visualizer.py?

**Comment by BenyaPyat** [comment]
Hi, I had pip install issues with jupyter that were unresolved that I just went through (jupyter-client didn't properly install the correct version or something of that sort) and I was able to get it working. Thank you for your help though!

**Comment by rickwierenga** [comment]
Glad it's working now! Please open a new issue if you have any other questions :)
