### ISSUE TITLE
Mistake in documentation?

### ISSUE THREAD

**Issue by yachty66** [PyLabRobot/pylabrobot#8]
I was trying to run the simulation with the code from the documentation:

```python
from pylabrobot.liquid_handling.backends.simulation.simulator_backend import SimulatorBackend
from pylabrobot.liquid_handling import LiquidHandler

from pylabrobot.liquid_handling.resources import (
    TIP_CAR_480_A00,
    PLT_CAR_L5AC_A00,
    Cos_96_DW_1mL,
    STF_L
)

sb = SimulatorBackend()
lh = LiquidHandler(backend=sb)

lh.setup()
```

This didn't started the simulation and instead resulted in an error:

`
Exception ignored in: <function LiquidHandler.__del__ at 0x1125a77f0>
Traceback (most recent call last):
  File "/Users/maxhager/Projects2022/KiwiBiolab/PyLabRobot/pylabrobot/pylabrobot/liquid_handling/liquid_handler.py", line 79, in __del__
    if self.setup_finished:
AttributeError: 'LiquidHandler' object has no attribute 'setup_finished'
Traceback (most recent call last):
  File "/Users/maxhager/Projects2022/KiwiBiolab/PyLabRobot/simulation.py", line 12, in <module>
    lh = LiquidHandler(backend=sb)
TypeError: LiquidHandler.__init__() missing 1 required positional argument: 'deck'
`

What worked for me was adding `from pylabrobot.liquid_handling.resources.hamilton import STARLetDeck` as an import and using it for `lh = LiquidHandler(backend=sb, deck=STARLetDeck())`.

**Comment by rickwierenga** [comment]
Thanks for highlighting this.

The simulator tutorial was outdated on multiple fronts, including #5. It has been fixed in https://github.com/PyLabRobot/pylabrobot/commit/83151f98aeeb55c7320bb363b804ed54e798aacf.
