### ISSUE TITLE
from pylabrobot import LiquidHandler

### ISSUE THREAD

**Issue by evancollins1** [PyLabRobot/pylabrobot#90]
Hi,

I believe the first line of the demo in the readme should be

`from pylabrobot.liquid_handling import LiquidHandler`

(instead of `from pylabrobot import LiquidHandler`)

Cool project!

**Comment by rickwierenga** [comment]
fixed with https://github.com/PyLabRobot/pylabrobot/commit/cbb5bf6a309b6bec77879caa4962a17f41e730d5.

Thanks!
